### ISSUE TITLE
Understanding the `before` options (specifically for authorization layer)

### ISSUE THREAD

**Issue by charlie-s** [almost-full-stack/sequelize-graphql-schema#26]
First – thanks for this library. Really moving quickly with it, and have the start of an elegant new codebase for our API. Our structure for models and custom mutations/queries is very clean and easy to extend, and we get the power of Sequelize at the persistence layer.

We're trying to implement authorization at the most appropriate layer. We already have authentication handled up front (directly in a Koa middleware function, not via `authorizer` although I'm curious if there's any benefit there), and the current user + role is available to all queries/mutations via `context`. We've looked into graphql-shield and directives, but it seems that those routes may get us bloated rather quickly, and we'd like to start very small and focused.

It seems like attaching permission definitions to our models via the `.graphql` property and using `before:*` to check the current context + action could be a good way to go, but I'm new to GraphQL and don't understand what the before options of "create, fetch, destroy and update" are. Who determines what queries fall into these categories, or are these Sequelize hooks? What categories do my custom mutations and queries fall into?

If you've got a better recommendation, we'd love to hear it. Thanks.

**Comment by alirizwan** [comment]
You are welcome. You can use before hooks (these are not sequelize hooks but hooks for your graphql api) however this is not recommended for 2 reasons: a) These hooks won't run before your custom queries/mutations. b) These are not generic hooks i.e once done for all.

I would highly recommend to use authorizer function since that's built for this purpose Authentication or Permissions/ACL. This function will give you the ability to put your ACL logic in one place and this function runs before every query or mutation regardless of it being custom or auto created. From authorizer you can calculate your permissions and then pass those in your context or if something is not allowed you can simply throw an Error.

There is an extensive update coming up as well if you have any suggestions we would love to consider those.

**Comment by charlie-s** [comment]
Thanks for getting back so quickly, this answers my questions really well.

I'll play with authorizer and debug to see when it runs in relation to default queries and custom resolvers. Context should work perfectly for us. 

We have a route for authenticating – I imagine in the authorizer we'll just check if that's the current route and run the auth logic there, or skip and allow it to pass to the auth mutation?

**Comment by alirizwan** [comment]
In authorizer you can do your ACL however you want. It's the very first function which runs before anything happens. You can block the flow here or let it pass.

**Comment by charlie-s** [comment]
👍

**Comment by jasp402** [comment]
Sorry for resuming a thread that had already been closed.
However, I am desperate, I am using the function` Authorizer`
In the "option" as follows:

```
const option = {
	authorizer: function authorizer(source, args, context, info) {
		const { fieldName } = info;
		console.log(fieldName)
		if(fieldName === 'confirmEmail'){
			return Promise.resolve(false);
		}else{
			return Promise.resolve(true);
		}
	}
}
const {generateSchema} = require('sequelize-graphql-schema')(option);
```


And those that I want to do is reject the consultations that are equal to a given value.

But when returning the promise with the value "false". The consultation is executed. I must be doing something wrong. But I can not find a lot of information about how to handle the middleware.

**Comment by alirizwan** [comment]
> return Promise.resolve(false);

This must be `return Promise.reject();` when you resolve a promise, regardless of it's value, it's considered a success unless you reject it.
