### ISSUE TITLE
Custom attributes and resolvers

### ISSUE THREAD

**Issue by emanuelet** [almost-full-stack/sequelize-graphql-schema#27]
I'm trying to add a custom attribute to my model with a custom resolver to be able to calculate the value based on the record data.

Can you advise how I can do it? So far I've been able to add the field but I'm not able to connect the resolver correctly (or I don't know if  even that's possible)

This is one of the things I've tried: 
```javascript
hotels.graphql = {
    attributes: {
      include: { key: 'string', lead_image: 'string' },
    },
    extend: {
      fetch: (data, source, args, context, info) => {
        data.lead_image = 'Added by extension.'
  
        return data
      },
    },
  }
```

Thank for any help

**Comment by alirizwan** [comment]
I would prefer to use virtual fields feature provided by sequelize itself, reasoning is include wouldn't add the field to the model itself instead it adds that field in graphql type. In extend data is a sequelize instance and you cannot do data.lead_image since the attribute is not present in the model itself. i would recommend to create two virtual fields in your model since it seems like you want these fields in the model.
in that case you would define your keys in model like this:
`lead_image: {
      type: DataTypes.VIRTUAL(DataTypes.STRING, []),
      get() {
        if you want to do calculations here you can do here or in extend
      }
    }`

**Comment by emanuelet** [comment]
it worked very well. Thank you very much for your help
