### ISSUE TITLE
Error when closing database connection using dataloader with model associations

### ISSUE THREAD

**Issue by RenatoFranze** [almost-full-stack/sequelize-graphql-schema#30]
Hi there! 

First of all: thanks for this amazing project and sorry for any english mistake in advance, :)

I'm developing a Grapqhl project in AWS Lambda and, because of the nature of serverless environment, it's necessaire to close and redo the connection between requests. 

All works fine if I hit just only one model per request, but, if I try to take advantage of model associations, my application breaks in the second request with the following message:

"ConnectionManager.getConnection was called after the connection manager was closed!"

As you can see in the images below, the first request works flawless but the second one throwns the error after selecting the first table.

First request:
![image](https://user-images.githubusercontent.com/10964864/64450236-10725900-d0b8-11e9-80f7-3296ad506bc9.png)

Second request:
![image](https://user-images.githubusercontent.com/10964864/64450264-1ec07500-d0b8-11e9-8324-33b00313b045.png)

Query log:
![image](https://user-images.githubusercontent.com/10964864/64450589-da81a480-d0b8-11e9-9bf8-a3b8b107767a.png)

Here is my lambda handler:
```js
const { ApolloServer } = require('apollo-server-lambda');
const { GraphQLSchema } = require('graphql');
const { generateSchema } = require('sequelize-graphql-schema')({
    dataloader: true
});

const Db = require('../../models/autologpod');

const buildGraphQlContext = ({ context, event }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context
});

const runHandler = (event, context, handler) =>
    new Promise((resolve, reject) => {
        const callback = (error, body) => (error ? reject(error) : resolve(body));

        handler(event, context, callback);
    }
);

const run = async (event, context) => {    
    let autologpod = await new Db(event.pathParameters.account_id);

    const server = new ApolloServer({
        schema: new GraphQLSchema(await generateSchema(autologpod.db)),
        context: buildGraphQlContext,
    });

    const handler = server.createHandler({ cors: { credentials: true, origin: '*' } });
    const response = await runHandler(event, context, handler);
    
    await autologpod.close();

    return response;
};

exports.graphqlHandler = run;
```
If I remove the dataloader option, the error is gone. Can any one help me or point a direction? Thanks!

**Comment by alirizwan** [comment]
Hi, there are two things, first check what version of sequelize are you using, if it's sequelize 5.0 then you shouldn't close your connection since sequelize 5.0 takes care of that.

But let's say you have this issue regardless of sequelize version, you need to clear your dataloader cache. dataloader caches your connection as well and tries to reuse it even after it is explicitly closed. To fix this you must clear data loader cache as soon as you close your connection, to do that library is already exposing a function `resetCache` you should use that and call this right after or right before you close your connection.

`const { generateSchema, resetCache } = require('sequelize-graphql-schema')({
    dataloader: true
});` 
`await autologpod.close(); resetCache()`

Although I don't recommend closing your connection and resetting cache like you are doing rather close it inside your handler.

**Comment by RenatoFranze** [comment]
Hi alirizwan, thanks for your fast reply!

Using resetCache(); did indeed fix the problem! 

I'm using Sequelize 5.16 and never knew they have worked out the connection on lambas. I always saw sleeping connections waiting for the mysql timeout to clear them out. I will do more tests and I'm hoping for this aewsome behavior, since opening and closing connections adds up some quite overhead on lambdas. 

Any way, thanks a lot!
